server:
  port: 8888
# CONFIGURACION CON GIT
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ajulcala/ports-xl
 #         default-label: main
 #         clone-on-start: true
 #         force-pull: true
 #     discovery:
 #       enabled: false

  #  cloud:
  #    config:
  #        server:
  #          native:
  #            search-locations: file:///C:\Ambiente-desarrollo\dockerizar\admin-config-data
  #  profiles:
  #    active: native


# EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka #de manera local
      #defaultZone: http://eureka-server:8761/eureka #se llama al contenedor del docker
    register-with-eureka: true
    fetch-registry: true